logging:
  level:
    root: info
 # file:
 #   name: landing.log
 #   path: C:/logs
 #   max-size: 1MB
    
spring:
  datasource:
       url: jdbc:mysql://localhost:3308/landing?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
       username: root
       password: 25262728
       driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
  data: 
    mongodb:
      uri: mongodb://system:25262728@localhost:27017/landing
      auto-index-creation: true           
  
    
    

